### PR TITLE
Move kube-inject to wharfie

### PR DESCRIPTION
**Pull request by kyessenov**

### CODE REVIEW

**Comment by kyessenov** [comment]
The injection algorithm is identical between AC and kube-inject. Let's keep the code here since it makes no sense to duplicate the injection in two repos.

**Comment by rshriram** [comment]
Can we rename this repo to kube-inject? This seems to be for k8s only and it has a "single" well defined  purpose unlike other repos, ie proxy injection in kube. 

We have many components now in istio. Having pet names for each component will make it hard for people to catch onto the istio concepts/arch when we present it externally, or when potential contributors browse through our repos

**Comment by andraxylia** [comment]
I like kube-inject also, and indeed it will make clear the purpose of this repo. I renamed it.

(I had thought we must name the repos with sailing terms. Wharfie is not a pet name, it's a person who loads/unloads containers on a ship:
https://www.merriam-webster.com/dictionary/wharfie)

**Comment by rshriram** [comment]
By pet name, I meant names like Wharfie vs functional sounding names like kube-inject. I didn't literally mean pet 😜, though I will remember this name for sure!

**Pull request closed without merging**
